add_item classmethods
elenirotsides/Exchange4Students pull request #16
Opened 2021-04-01 03:56 UTC by elenirotsides

closes #14
Temporary add_item class methods for the purposes of getting the rest of the website going. So far, I've only completed add_book, will add to this pr as I complete the rest.﻿

2021-04-01 20:22 UTC, carpenterd777 requested changes

2021-04-01 20:22 UTC, carpenterd777 commented on src/e4stypes/book_item.py
> +                 course_number: int) -> Book:
all of these parameters are already handled when creating a `BookItem`. Instead of passing each field of `BookItem` as a parameter here, we should just pass a `BookItem` and access the fields while creating the dictionary. Same will be true for each other variation of `add_item`.

More of a nitpick, but also if we call these all `add_item()` we may be able to utilize polymorphism.

```suggestion
    def add_item(cls, title: str, desc: str, price: Decimal, weight: float,
                 seller: str, book_title: str, edition: int,
                 course_number: int) -> BookItem:
```

2021-04-01 20:22 UTC, carpenterd777 commented on src/e4stypes/clothing_item.py
> +                     gender: ClothingGender, color: str):
```suggestion
    def add_item(cls, title: str, desc: str, price: Decimal, weight: float,
                     seller: str, garment_type: str, size: ClothingSize,
                     gender: ClothingGender, color: str) -> ClothingItem:
```

2021-04-01 20:22 UTC, carpenterd777 commented on src/e4stypes/electronic_item.py
> +                       model: str, dimensions: List[int]):
```suggestion
    def add_item(cls, title: str, desc: str, price: Decimal,
                       weight: float, seller: str, electronic_type: str,
                       model: str, dimensions: List[int]) -> ElectronicItem:
```

2021-04-01 20:22 UTC, carpenterd777 commented on src/e4stypes/furniture_item.py
> +                      color: str, dimensions: List[int]):
```suggestion
    def add_item(cls, title: str, desc: str, price: Decimal,
                      weight: float, seller: str, furnishing_type: str,
                      color: str, dimensions: List[int]) -> FurnitureItem:
```

2021-04-01 20:22 UTC, carpenterd777 commented on src/e4stypes/sports_gear_item.py
> +                        gender: ClothingGender):
```suggestion
    def add_item(cls, title: str, desc: str, price: Decimal,
                        weight: float, seller: str, gear_type: str, size: str,
                        gender: ClothingGender) -> SportsGearItem:
```

2021-04-01 21:15 UTC, elenirotsides commented on src/e4stypes/book_item.py
> +                 course_number: int) -> Book:
Makes sense, would the only thing I need to change in these functions are the changes you've annotated? Or is there something more to this that I just didn't understand? @carpenterd777

2021-04-01 21:26 UTC, carpenterd777 commented on src/e4stypes/book_item.py
> +                 course_number: int) -> Book:
you'd have to change the design of the method a bit. instead of being passed each of these parameters, the method would receive a `BookItem` that already exists. e.g.:
```
def add_item(cls, book : BookItem) -> BookItem:
```

then when creating the dictionary to send to mongo you'd access the fields of `book` either directly or using their getter methods.

2021-04-02 01:11 UTC, elenirotsides commented
@carpenterd777 Updated! Please let me know if I did something incorrectly!

2021-04-02 02:04 UTC, carpenterd777 requested changes

2021-04-02 02:04 UTC, dcarpenter31 commented on src/e4stypes/book_item.py
> +            'course_number': cls.course_number
still not quite. Remember that `cls` refers to the class itself, not any instance of it. Since these are instance attributes, to access them we need a particular instance of that class (`book`).
```suggestion
            'title': book.get_title(),
            'description': book.get_desc(),
            'price': book.get_price(),
            'weight': book.get_weight(),
            'seller': book.get_seller(),
            'book_title': book.get_book_title(),
            'edition': book.get_edition(),
            'course_number': book.get_course_number()
```

same is true for the other types.

2021-04-02 02:04 UTC, carpenterd777 commented on src/e4stypes/book_item.py
> +        return inserted_book
I'm not sure what the return type of `insert_one()` is, but `add_item()` is currently annotated to return a `BookItem`. I don't think that `inserted_book` is a `BookItem`. perhaps change this to return `book`, or change the annotation to the return type of `insert_one`. Same is true for the other types.

2021-04-02 02:11 UTC, elenirotsides commented on src/e4stypes/book_item.py
> +            'course_number': cls.course_number
Oh I see now! I originally tried doing something like `price: get_price()` and I was getting an error of sorts...I was missing the book class! Will fix these, thanks!

2021-04-02 02:16 UTC, elenirotsides commented on src/e4stypes/book_item.py
> +        return inserted_book
Not sure if this helps at all, but `insert_one` needs to take in a dictionary, which is the reason for the dictionaries I instantiate in all these methods. What is `BookItem` 's type? If its not a dictionary, then I need to rework these functions a bit I think @carpenterd777

2021-04-02 02:17 UTC, elenirotsides commented on src/e4stypes/book_item.py
> +        return inserted_book
Or alternatively, should these functions be returning anything at all?

2021-04-02 02:19 UTC, carpenterd777 commented on src/e4stypes/book_item.py
> +        return inserted_book
`BookItem` *is* the type, `book` is an instance of `BookItem`. I'm just not sure what `insert_one` returns, is it a dictionary? the documentation for pymongo might say

2021-04-02 02:32 UTC, carpenterd777 commented on src/e4stypes/book_item.py
> +        return inserted_book
I dont think these functions need to return anything as you said, in which case the annotation is `type(None)`

2021-04-02 03:18 UTC, elenirotsides commented on src/e4stypes/book_item.py
> +        return inserted_book
Ahhh, gotcha. Yeah, it returns a dictionary; I did some testing when I originally wrote these methods just to make sure I was doing this correctly. I'm going to make these return nothing though, since they are adding methods as opposed to `get_all` for example.

2021-04-02 15:57 UTC, gracemiguel approved these changes
might have some bugs but we just need to pull it to fiddle with it.

2021-04-02 16:09 UTC, merged